### ISSUE TITLE
n-grams BK-trees

### ISSUE THREAD

**Issue by BiotechPedro** [JuliaNeighbors/BKTrees.jl#3]
Hi 😄 

I am trying to collapse ~200 M sequences (that belong to ~50 M unique sequences) with different Hamming distances with a package called [UMICollapse](https://github.com/Daniel-Liu-c0deb0t/UMICollapse), but it's written in Java. It leverages n-grams BK-trees which seems more efficient according to the [publication of the developer](https://doi.org/10.7717/peerj.8275). 

Do you think it could be a good implementation to add this algorithm to BKTrees.jl? Do you also think that can be more efficient based on the features of Julia?

Thanks!

Pedro

**Comment by zgornel** [comment]
Hi,

Unfortunately I cannot answer your question as I am unfamiliar with n-gram bktrees. The best way to answer the question is, I suppose, implementing the algorithm and test its performance.
Ofcourse, you can open a PR once that's done and we can take it from there.
Best,
Corneliu

**Comment by BiotechPedro** [comment]
Hi Corneliu,

I am not yet familiar with Julia, so I do not think it's feasible. Just wanted to say here just in case it would be of interest.

Many thanks!

Pedro
